In [3]:
print("Hello World")

Hello World


In [4]:
a = int(input("Enter a number"))
print(a)

Enter a number 5


5


In [5]:
a = float(input("Enter a number"))
print(a)

Enter a number 5


5.0


In [6]:
a = int(input("Enter a number"))
b = int(input("Enter a number"))
c=a+b
print(c)

Enter a number 69
Enter a number 0


69


In [1]:
import numpy as np

In [8]:
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
#2D Array

a= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
#2D Array

a= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a.ndim)


2


In [16]:
#2D Array

a= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a.ndim)



2


In [20]:
a = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print(a.dtype)

int64


In [28]:
a = np.arange(2,30,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [7]:
a = np.array([1,2,3,4,5])
print(a.max())
print(a.min())
print(a.sum())

5
1
15


In [6]:
a = np.arange(1,13)
print(a.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
a = np.array([1,2,3,4,5])
print(a.max(),a.min())
print(a.sum(),a.mean())

5 1
15 3.0


In [9]:
a = np.array([1,2,3,4,5])
print(a.min()*2)

2


In [10]:
a = np.array([1,2,3,4,5])
print(a.min()/2)

0.5


In [11]:
a = np.array([1,2,3,4,5])
print(a[2])

3


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree

from sklearn.tree import export_graphviz
from IPython.display import Image
import pydotplus

import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd


sana = pd.read_csv("Indian_Employee_Data.csv")



In [18]:
sana.head()

,Employee_ID,Name,Age,Gender,Department,Position,Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
0,EMP001,Rajesh Kumar,32.0,Male,Engineering,Senior Developer,850000.0,8.0,Bangalore,Karnataka,B.Tech,4.2,03/15/2016,12.0,45.0
1,EMP002,Priya Sharma,28.0,Female,Marketing,Marketing Manager,720000.0,5.0,Mumbai,Maharashtra,MBA,4.5,01/20/2019,8.0,32.0
2,EMP003,Amit Singh,35.0,Male,Finance,Financial Analyst,650000.0,10.0,Delhi,Delhi,CA,3.8,07/10/2014,15.0,28.0
3,EMP004,Sneha Patel,26.0,Female,NaN,HR Executive,480000.0,3.0,Ahmedabad,Gujarat,MBA,4.1,05/12/2021,6.0,20.0
4,EMP005,Vikram Reddy,40.0,Male,Engineering,Tech Lead,1200000.0,15.0,Hyderabad,Telangana,M.Tech,4.7,11/08/2009,25.0,55.0


In [19]:
sana.tail()

,Employee_ID,Name,Age,Gender,Department,Position,Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
44,EMP045,Neha Kapoor,28.0,Female,IT,Data Analyst,NaN,4.0,Bangalore,Karnataka,M.Sc,3.8,04/12/2020,6.0,29.0
45,EMP046,Amit Sharma,27.0,Male,IT,Junior Developer,650000.0,4.0,Delhi,NaN,B.Tech,4.5,08/20/2020,5.0,25.0
46,EMP047,Riya Gupta,32.0,Female,HR,HR Specialist,NaN,8.0,Mumbai,Maharashtra,MBA,NaN,11/03/2016,inf,42.0
47,EMP048,Rohit Bansal,36.0,Male,Finance,Senior Analyst,980000.0,12.0,Mumbai,Maharashtra,CA,4.9,03/20/2012,19.0,51.0
48,EMP049,Sneha Tiwari,25.0,Female,Sales,Sales Representative,inf,2.0,Kolkata,West Bengal,B.Com,3.6,05/14/2022,3.0,16.0


In [23]:
print(sana.isnull())

    Employee_ID   Name    Age  Gender  Department  Position  Salary  \
0         False  False  False   False       False     False   False   
1         False  False  False   False       False     False   False   
2         False  False  False   False       False     False   False   
3         False  False  False   False        True     False   False   
4         False  False  False   False       False     False   False   
5         False  False  False   False       False     False   False   
6         False  False  False   False       False     False    True   
7         False  False  False   False       False     False   False   
8         False  False  False   False       False      True   False   
9         False  False  False   False       False     False   False   
10        False  False  False   False       False     False   False   
11        False  False   True   False       False     False   False   
12        False  False  False   False       False     False   False   
13    

In [3]:
print(sana.isnull().sum())

Employee_ID           0
Name                  0
Age                   2
Gender                0
Department            1
Position              1
Salary                5
Experience_Years      2
City                  0
State                 3
Education             0
Performance_Rating    4
Joining_Date          1
Projects_Completed    1
Overtime_Hours        1
dtype: int64


In [5]:
sana.dropna()

,Employee_ID,Name,Age,Gender,Department,Position,Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
0,EMP001,Rajesh Kumar,32.0,Male,Engineering,Senior Developer,850000.0,8.0,Bangalore,Karnataka,B.Tech,4.2,03/15/2016,12.0,45.0
1,EMP002,Priya Sharma,28.0,Female,Marketing,Marketing Manager,720000.0,5.0,Mumbai,Maharashtra,MBA,4.5,01/20/2019,8.0,32.0
2,EMP003,Amit Singh,35.0,Male,Finance,Financial Analyst,650000.0,10.0,Delhi,Delhi,CA,3.8,07/10/2014,15.0,28.0
4,EMP005,Vikram Reddy,40.0,Male,Engineering,Tech Lead,1200000.0,15.0,Hyderabad,Telangana,M.Tech,4.7,11/08/2009,25.0,55.0
5,EMP006,Kavya Nair,29.0,Female,Sales,Sales Executive,550000.0,4.0,Chennai,Tamil Nadu,B.Com,3.9,02/28/2020,inf,38.0
7,EMP008,Meera Joshi,27.0,Female,Design,UI/UX Designer,620000.0,4.0,Bangalore,Karnataka,B.Des,4.4,08/03/2020,7.0,25.0
9,EMP010,Anita Verma,38.0,Female,HR,HR Manager,950000.0,12.0,Gurgaon,Haryana,MBA,4.6,04/18/2012,18.0,48.0
10,EMP011,Suresh Iyer,42.0,Male,Engineering,Principal Engineer,1350000.0,18.0,Chennai,Tamil Nadu,M.Tech,4.8,01/25/2006,30.0,60.0
12,EMP013,Karan Chopra,30.0,Male,Sales,Sales Manager,780000.0,6.0,Mumbai,Maharashtra,MBA,4.2,06/22/2018,10.0,35.0
13,EMP014,Divya Rao,34.0,Female,Engineering,Data Scientist,950000.0,8.0,Bangalore,Karnataka,M.Sc,4.5,10/05/2016,14.0,40.0


In [6]:
sana.fillna(0)

,Employee_ID,Name,Age,Gender,Department,Position,Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
0,EMP001,Rajesh Kumar,32.0,Male,Engineering,Senior Developer,850000.0,8.0,Bangalore,Karnataka,B.Tech,4.2,03/15/2016,12.0,45.0
1,EMP002,Priya Sharma,28.0,Female,Marketing,Marketing Manager,720000.0,5.0,Mumbai,Maharashtra,MBA,4.5,01/20/2019,8.0,32.0
2,EMP003,Amit Singh,35.0,Male,Finance,Financial Analyst,650000.0,10.0,Delhi,Delhi,CA,3.8,07/10/2014,15.0,28.0
3,EMP004,Sneha Patel,26.0,Female,0,HR Executive,480000.0,3.0,Ahmedabad,Gujarat,MBA,4.1,05/12/2021,6.0,20.0
4,EMP005,Vikram Reddy,40.0,Male,Engineering,Tech Lead,1200000.0,15.0,Hyderabad,Telangana,M.Tech,4.7,11/08/2009,25.0,55.0
5,EMP006,Kavya Nair,29.0,Female,Sales,Sales Executive,550000.0,4.0,Chennai,Tamil Nadu,B.Com,3.9,02/28/2020,inf,38.0
6,EMP007,Arjun Gupta,31.0,Male,Engineering,DevOps Engineer,0.0,7.0,Pune,Maharashtra,B.Tech,4.3,09/14/2017,11.0,42.0
7,EMP008,Meera Joshi,27.0,Female,Design,UI/UX Designer,620000.0,4.0,Bangalore,Karnataka,B.Des,4.4,08/03/2020,7.0,25.0
8,EMP009,Rohit Agarwal,33.0,Male,Finance,0,580000.0,9.0,Kolkata,West Bengal,M.Com,3.7,12/01/2015,13.0,30.0
9,EMP010,Anita Verma,38.0,Female,HR,HR Manager,950000.0,12.0,Gurgaon,Haryana,MBA,4.6,04/18/2012,18.0,48.0


In [7]:
sana.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Employee_ID         49 non-null     object 
 1   Name                49 non-null     object 
 2   Age                 47 non-null     float64
 3   Gender              49 non-null     object 
 4   Department          48 non-null     object 
 5   Position            48 non-null     object 
 6   Salary              44 non-null     float64
 7   Experience_Years    47 non-null     float64
 8   City                49 non-null     object 
 9   State               46 non-null     object 
 10  Education           49 non-null     object 
 11  Performance_Rating  45 non-null     float64
 12  Joining_Date        48 non-null     object 
 13  Projects_Completed  48 non-null     float64
 14  Overtime_Hours      48 non-null     float64
dtypes: float64(6), object(9)
memory usage: 5.9+ KB


In [12]:
sana.shape

(49, 15)

In [13]:
sana.dtypes

Employee_ID            object
Name                   object
Age                   float64
Gender                 object
Department             object
Position               object
Salary                float64
Experience_Years      float64
City                   object
State                  object
Education              object
Performance_Rating    float64
Joining_Date           object
Projects_Completed    float64
Overtime_Hours        float64
dtype: object

In [ ]:
sana